baseAPIRoute: "https://192.168.51.19:5000/eMosaicREST/"
username: "USU"
password: "eMosaic-usu"
urls:
  setUcSession: "site/SetUCsessions/"
  getChargeSessions: "site/GetChargeSessions/"
  getPrices: "site/GetPrices/"
  getPrice: "site/GetPrice/"
  setPrice: "site/SetPrice/"
  setClearCs: "site/SetClearCS/"
  setEVSEs: "site/SetEVSEs/"
  setEvModels: "site/SetEVmodels/"
  setCsStart: "sessions/SetCSstart/"
  setCsRegUpdate: "sessions/SetCSregupdate/"
  setCsEnd: "sessions/SetCSend/"
  setReservation: "reservations/SetReservation/"
  setArrival: "buses/SetArrival/"
  setDeparture: "buses/SetDeparture/"